### ISSUE TITLE
4.2.1 -> 4.2.2 Upgrade breaks Puma startup

### ISSUE THREAD

**Issue by tadasant** [appsignal/appsignal-ruby#1348]
If your bug is about how AppSignal works in your app specifically we recommend you contact us at support@appsignal.com with your bug report instead.

---

## Describe the bug

I noticed this when our CI/CD started breaking on a PR that is solely an upgrade from 4.2.1 to 4.2.2.

Here's the stacktrace:

```
Puma caught this error: wrong number of arguments (given 0, expected 1) (ArgumentError)
/Users/admin/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/appsignal-4.2.2/lib/appsignal/logger.rb:162:in `push_tags'
/Users/admin/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-8.0.0.1/lib/active_support/broadcast_logger.rb:243:in `block in method_missing'
/Users/admin/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-8.0.0.1/lib/active_support/broadcast_logger.rb:243:in `map'
/Users/admin/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-8.0.0.1/lib/active_support/broadcast_logger.rb:243:in `method_missing'
/Users/admin/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/railties-8.0.0.1/lib/rails/rack/logger.rb:24:in `call'
/Users/admin/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/actionpack-8.0.0.1/lib/action_dispatch/middleware/remote_ip.rb:96:in `call'
/Users/admin/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/actionpack-8.0.0.1/lib/action_dispatch/middleware/request_id.rb:34:in `call'
/Users/admin/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rack-3.1.8/lib/rack/method_override.rb:28:in `call'
/Users/admin/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rack-3.1.8/lib/rack/runtime.rb:24:in `call'
/Users/admin/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-8.0.0.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/Users/admin/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/actionpack-8.0.0.1/lib/action_dispatch/middleware/server_timing.rb:61:in `block in call'
/Users/admin/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/actionpack-8.0.0.1/lib/action_dispatch/middleware/server_timing.rb:26:in `collect_events'
/Users/admin/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/actionpack-8.0.0.1/lib/action_dispatch/middleware/server_timing.rb:60:in `call'
/Users/admin/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/actionpack-8.0.0.1/lib/action_dispatch/middleware/executor.rb:16:in `call'
/Users/admin/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/actionpack-8.0.0.1/lib/action_dispatch/middleware/static.rb:27:in `call'
/Users/admin/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rack-3.1.8/lib/rack/sendfile.rb:114:in `call'
/Users/admin/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/actionpack-8.0.0.1/lib/action_dispatch/middleware/host_authorization.rb:143:in `call'
/Users/admin/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/rack-3.1.8/lib/rack/events.rb:116:in `call'
/Users/admin/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/railties-8.0.0.1/lib/rails/engine.rb:535:in `call'
/Users/admin/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/puma-6.5.0/lib/puma/configuration.rb:279:in `call'
/Users/admin/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/puma-6.5.0/lib/puma/request.rb:99:in `block in handle_request'
/Users/admin/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/puma-6.5.0/lib/puma/thread_pool.rb:389:in `with_force_shutdown'
/Users/admin/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/puma-6.5.0/lib/puma/request.rb:98:in `handle_request'
/Users/admin/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/puma-6.5.0/lib/puma/server.rb:468:in `process_client'
/Users/admin/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/puma-6.5.0/lib/puma/server.rb:249:in `block in run'
/Users/admin/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/puma-6.5.0/lib/puma/thread_pool.rb:166:in `block in spawn_thread'
```

## To Reproduce

- Use puma 6.5.0 with Rails 8.0.0.1
- My logging initializer is:

```
appsignal_logger = Appsignal::Logger.new("rails")
Rails.logger.broadcast_to(appsignal_logger)
```

Let me know if you need more details.

**Comment by tombruijn** [comment]
Hi @tadasant, I made a fix for this in https://github.com/appsignal/appsignal-ruby/pull/1350
Please downgrade for now and update when our next with this fix is out :)

**Comment by unflxw** [comment]
Hi @tadasant, thank you for reporting this issue. We have just released AppSignal for Ruby 4.2.3, with a fix for this issue.

**Comment by jeffbax** [comment]
Hey folks, I am still seeing this error as Puma boots with `4.2.3` -- with this stack

```
Puma caught this error: wrong number of arguments (given 0, expected 1) (ArgumentError)
.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/appsignal-4.2.3/lib/appsignal/logger.rb:154:in `tagged'
.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-7.1.5.1/lib/active_support/broadcast_logger.rb:243:in `block in method_missing'
.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-7.1.5.1/lib/active_support/broadcast_logger.rb:243:in `map'
.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-7.1.5.1/lib/active_support/broadcast_logger.rb:243:in `method_missing'
.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/railties-7.1.5.1/lib/rails/rack/logger.rb:24:in `call'
.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/actionpack-7.1.5.1/lib/action_dispatch/middleware/remote_ip.rb:92:in `call'
.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/rack-timeout-0.6.3/lib/rack/timeout/core.rb:111:in `call'
.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/request_store-1.7.0/lib/request_store/middleware.rb:19:in `call'
.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/actionpack-7.1.5.1/lib/action_dispatch/middleware/request_id.rb:28:in `call'
.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/rack-2.2.10/lib/rack/method_override.rb:24:in `call'
.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/rack-2.2.10/lib/rack/runtime.rb:22:in `call'
.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-7.1.5.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/actionpack-7.1.5.1/lib/action_dispatch/middleware/server_timing.rb:59:in `block in call'
.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/actionpack-7.1.5.1/lib/action_dispatch/middleware/server_timing.rb:24:in `collect_events'
.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/actionpack-7.1.5.1/lib/action_dispatch/middleware/server_timing.rb:58:in `call'
.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/actionpack-7.1.5.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/actionpack-7.1.5.1/lib/action_dispatch/middleware/static.rb:25:in `call'
.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/rack-2.2.10/lib/rack/sendfile.rb:110:in `call'
.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/actionpack-7.1.5.1/lib/action_dispatch/middleware/host_authorization.rb:141:in `call'
.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/rack-2.2.10/lib/rack/events.rb:112:in `call'
.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/utf8-cleaner-1.0.0/lib/utf8-cleaner/middleware.rb:21:in `call'
.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/shakapacker-8.0.2/lib/shakapacker/dev_server_proxy.rb:25:in `perform_request'
.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/rack-proxy-0.7.7/lib/rack/proxy.rb:87:in `call'
.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/railties-7.1.5.1/lib/rails/engine.rb:536:in `call'
.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/puma-6.5.0/lib/puma/configuration.rb:279:in `call'
.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/puma-6.5.0/lib/puma/request.rb:99:in `block in handle_request'
.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/puma-6.5.0/lib/puma/thread_pool.rb:389:in `with_force_shutdown'
.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/puma-6.5.0/lib/puma/request.rb:98:in `handle_request'
.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/puma-6.5.0/lib/puma/server.rb:468:in `process_client'
.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/puma-6.5.0/lib/puma/server.rb:249:in `block in run'
.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/puma-6.5.0/lib/puma/thread_pool.rb:166:in `block in spawn_thread'
```

* Appsignal @ 4.2.3
* Rails @ 7.1.5.1
* Puma @ 6.5.0
* Rack @ 2.2.10

**Comment by unflxw** [comment]
Hi @jeffbax, thank you for reporting this. The issue in your backtrace is actually that at #1349. There will be a fix for it shortly; in the meantime, consider downgrading to AppSignal for Ruby 4.2.1.

**Comment by unflxw** [comment]
Hi @jeffbax,

We've now released AppSignal for Ruby 4.3.0, which fixes several issues adjacent to this one. We recommend upgrading to it.

If you use `ActiveSupport::BroadcastLogger` (the `#broadcast_to` method in `Rails.logger`) to send logs to several loggers, see [our Rails logging documentation](https://docs.appsignal.com/logging/integrations/ruby.html#rails-logger) for our recommended alternative.

**Comment by tadasant** [comment]
Thanks! Confirming that my upgrade from 4.2.1 -> 4.3.1 went smoothly.

**Comment by jeffbax** [comment]
@unflxw sorry -- let me know if you prefer a new issue but was keeping things here for continuity sake...

I got it running with 4.3.1, but (while kind of minor) one of the things I'm noticing is that it seems like this new configuration is adding additional line breaks between each line logged...

Setting things up via a Rails config block:
```
Rails.application.configure do
  rails_appsignal_logger = Appsignal::Logger.new(
    'rails',
    format: Appsignal::Logger::LOGFMT,
    level: Logger::Severity.coerce(config.log_level),
  )

  rails_appsignal_logger.broadcast_to(Rails.logger)
  Rails.logger = ActiveSupport::TaggedLogging.new(rails_appsignal_logger)
end
```

Appsignal on:
<img width="1102" alt="image" src="https://github.com/user-attachments/assets/6bd2ec73-bf81-43f5-802a-bd20af406e2f" />

Appsignal off:
<img width="1102" alt="image" src="https://github.com/user-attachments/assets/57b8243c-8fbd-4d75-82c4-c1075d4e41b3" />

Not sure if this is intended or not, it was not doing this with previously recommended code:
```
# note that this was NOT wrapping the rails logger with the tagged logging before, as it didn't seem to be working
rails_appsignal_logger = Appsignal::Logger.new(
  'rails',
  format: Appsignal::Logger::LOGFMT,
  level: Logger::Severity.coerce(config.log_level),
)

Rails.logger.broadcast_to(rails_appsignal_logger)
```

**Comment by unflxw** [comment]
Hi @jeffbax, thank you for reporting this! I have created a separate issue for that: #1360
